Repository drikusroor/ohayo-goededagu, pull requests merged in 2023-09, with the labels that each got.

#87 fix: Fix cover image issue
  README.md
  web/src/components/Post/PostForm/PostForm.tsx
  web/src/components/Upload/Upload/Upload.tsx
Labels: bug

#91 Ci/add GitHub actions workflow
  .github/workflows/ci.yml
  api/src/directives/requireAuth/requireAuth.test.ts
  api/src/directives/requireAuth/requireAuth.ts
  api/src/services/adminPosts/adminPosts.scenarios.ts
  api/src/services/adminPosts/adminPosts.test.ts
  api/src/services/comments/comments.scenarios.ts
  api/src/services/comments/comments.test.ts
  api/src/services/comments/comments.ts
  api/src/services/images/images.scenarios.ts
  api/src/services/posts/posts.scenarios.ts
  api/src/services/posts/posts.test.ts
  api/src/services/profiles/profiles.scenarios.ts
  api/src/services/profiles/profiles.test.ts
  api/src/services/profiles/profiles.ts
  api/src/services/thumbs/thumbs.scenarios.ts
  web/src/components/AccountCell/AccountCell.test.tsx
  web/src/components/Article/Article.test.tsx
  web/src/components/ArticleCell/ArticleCell.test.tsx
  web/src/components/ArticlesCell/ArticlesCell.test.tsx
  web/src/components/Comment/Comment.test.tsx
  web/src/components/EditAccountCell/EditAccountCell.test.tsx
  web/src/components/Profile/Profiles/Profiles.tsx
  web/src/components/ReisgenootschapCell/ReisgenootschapCell.test.tsx
  web/src/components/Thumb/Thumb.test.tsx
  web/src/components/Thumbs/Thumbs.test.tsx
  web/src/fixtures/get-article.fixture.ts
  web/src/pages/Account/EditAccountPage/EditAccountPage.test.tsx
Labels: enhancement

#102 use upload for profile picture #58
  api/src/graphql/adminPosts.sdl.ts
  web/src/components/Post/EditPostCell/EditPostCell.tsx
  web/src/components/Post/PostForm/PostForm.tsx
  web/src/components/Profile/Profile/Profile.tsx
  web/src/components/Profile/ProfileForm/ProfileForm.tsx
  web/src/components/Upload/Upload/Upload.tsx
Labels: enhancement

#109 Chore: Update RedwoodJS v6.0.0
  api/package.json
  api/src/services/adminPosts/adminPosts.test.ts
  package.json
  web/package.json
  web/src/entry.client.tsx
  web/src/pages/FatalErrorPage/FatalErrorPage.tsx
  web/vite.config.ts
  yarn.lock
Labels: enhancement

#117 Added: Post Location and LocationPin component
  api/db/migrations/20230908073014_add_post_location_column/migration.sql
  api/db/schema.prisma
  api/src/graphql/adminPosts.sdl.ts
  api/src/graphql/posts.sdl.ts
  api/src/services/posts/posts.scenarios.ts
  package.json
  scripts/seed.ts
  web/src/components/Article/components/ArticleArticle.tsx
  web/src/components/Article/components/ArticleChotto.tsx
  web/src/components/Article/components/ArticleVideo.tsx
  web/src/components/Article/components/helpers/extract-video-id.ts
  web/src/components/ArticleCell/ArticleCell.tsx
  web/src/components/ArticlesCell/ArticlesCell.tsx
  web/src/components/Avatar/AvatarTimestamp/AvatarTimestamp.tsx
  web/src/components/LocationPin/LocationPin.stories.tsx
  web/src/components/LocationPin/LocationPin.test.tsx
  web/src/components/LocationPin/LocationPin.tsx
  web/src/components/Post/EditPostCell/EditPostCell.tsx
  web/src/components/Post/MyPostsCell/MyPostsCell.tsx
  web/src/components/Post/PostCell/PostCell.tsx
  web/src/components/Post/PostForm/PostForm.tsx
  web/src/components/Post/PostsCell/PostsCell.tsx
  web/src/components/Upload/Preview/Preview.tsx
  web/src/components/Upload/Upload/Upload.tsx
  yarn.lock
Labels: feature, backend

#100 Feat/61 photo gallery
  api/src/graphql/adminPosts.sdl.ts
  api/src/services/adminPosts/adminPosts.ts
  api/src/services/adminPosts/helpers/upsert-image-galleries-on-post.ts
  api/src/services/posts/posts.ts
  package-lock.json
  scripts/seed.ts
  web/src/components/Article/Article.stories.tsx
  web/src/components/Article/Article.tsx
  web/src/components/Article/components/ArticleArticle/ArticleArticle.stories.tsx
  web/src/components/Article/components/ArticleArticle/ArticleArticle.tsx
  web/src/components/Article/components/ArticleChotto/ArticleChotto.stories.tsx
  web/src/components/Article/components/ArticleChotto/ArticleChotto.tsx
  web/src/components/Article/components/ArticleHaiku/ArticleHaiku.stories.tsx
  web/src/components/Article/components/ArticleHaiku/ArticleHaiku.tsx
  web/src/components/Article/components/ArticlePhotoGallery/ArticlePhotoGallery.stories.tsx
  web/src/components/Article/components/ArticlePhotoGallery/ArticlePhotoGallery.test.tsx
  web/src/components/Article/components/ArticlePhotoGallery/ArticlePhotoGallery.tsx
  web/src/components/Article/components/ArticlePreview/ArticlePreview.stories.tsx
  web/src/components/Article/components/ArticlePreview/ArticlePreview.tsx
  web/src/components/Article/components/ArticleVideo/ArticleVideo.stories.tsx
  web/src/components/Article/components/ArticleVideo/ArticleVideo.tsx
  web/src/components/ArticlesCell/ArticlesCell.tsx
  web/src/components/PhotoGrid/PhotoGrid.stories.tsx
  web/src/components/PhotoGrid/PhotoGrid.tsx
  web/src/components/Post/EditPostCell/EditPostCell.tsx
  web/src/components/Post/PostForm/PostForm.tsx
  web/src/components/Post/PostForm/TypeForms/VideoForm.tsx
  web/src/components/Profile/ProfileForm/ProfileForm.tsx
  web/src/components/Upload/Preview/Preview.tsx
  web/src/components/Upload/Upload/Upload.tsx
  web/src/fixtures/get-article.fixture.ts
  web/src/lib/formatters.tsx
  web/src/pages/ForgotPasswordPage/ForgotPasswordPage.tsx
  web/src/pages/LoginPage/LoginPage.tsx
  web/src/pages/SignupPage/SignupPage.tsx
  yarn.lock
Labels: feature

#147 Added: Improve user moderation
  api/src/graphql/users.sdl.ts
  api/src/services/users/users.ts
  web/src/components/Button/Button.tsx
  web/src/components/UserModerationCell/UserModerationCell.mock.ts
  web/src/components/UserModerationCell/UserModerationCell.test.tsx
  web/src/components/UserModerationCell/UserModerationCell.tsx
Labels: enhancement
